services:
  weenie-hut-api:
    profiles:
      - deploy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weenie-hut-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - psql_bp
      - minio
    environment:
      - DB_HOST=psql_bp
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=weenie-hut-dev
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=team-solid
      - MINIO_SECRET_KEY=@team-solid
      - MINIO_BUCKET_NAME=images
  
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: weenie-hut-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/sprint/data
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: team-solid
      MINIO_ROOT_PASSWORD: "@team-solid"
      MINIO_DEFAULT_BUCKETS: images
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 1m
      retries: 5
    volumes:
      - minio_volume:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
  createBucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set solid http://minio:9000 team-solid @team-solid &&
      /usr/bin/mc mb solid/images
      "
  setPublicBucket:
    image: minio/mc
    depends_on:
      createBucket:
        condition: service_completed_successfully
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set solid http://minio:9000 team-solid @team-solid &&
      /usr/bin/mc anonymous set public solid/images
      "

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    expose:
      - "16686"
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    command: 
      - "--memory.max-traces"
      - "1000"
      - "--collector.otlp.grpc.host-port"
      - ":4317"
      - "--collector.otlp.http.host-port"
      - ":4318"
    restart: always
volumes:
  psql_volume_bp:
  minio_volume:
