// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID              int64
	UserID          int64
	ActivityType    string
	DoneAt          pgtype.Timestamp
	DurationMinutes int32
	CaloriesBurned  int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         pgtype.Text
	Preference   pgtype.Text
	WeightUnit   pgtype.Text
	HeightUnit   pgtype.Text
	Weight       pgtype.Numeric
	Height       pgtype.Numeric
	ImageUri     pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
