name: Build and Push

on:
  push:
    branches: [main]
  workflow_dispatch: 
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
        default: 'main'
        type: string
env:
  REGISTRY: us-west1-docker.pkg.dev
  TAG: projectsprint-000001/ps-docker-repo/solid-weenie-hut
  COMMIT_TAG: ""
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Set branch and commit info
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          BRANCH_NAME="${{ github.event.inputs.branch }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "COMMIT_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "SAFE_BRANCH_NAME=$(echo ${BRANCH_NAME} | sed 's/[^a-zA-Z0-9.-]/-/g')" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.9.0

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.10
      with:
        credentials_json: ${{ secrets.REGISTRY_SA_KEY }}
        
    - name: Configure Docker for Google Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGISTRY }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.TAG }}:${{ env.COMMIT_TAG }}
          ${{ env.REGISTRY }}/${{ env.TAG }}:${{ env.SAFE_BRANCH_NAME }}-${{ env.COMMIT_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
